# Generated by Django 4.2.25 on 2025-10-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='min',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='form',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
