# Generated by Django 4.2.25 on 2025-10-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_form_min_alter_form_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='form',
        ),
        migrations.AddField(
            model_name='process',
            name='forms',
            field=models.ManyToManyField(related_name='processes', to='form.form'),
        ),
        migrations.AddField(
            model_name='process',
            name='name',
            field=models.CharField(default='process', max_length=255),
        ),
    ]
