# Generated by Django 4.2.25 on 2025-10-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_process_form_process_forms_process_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='form',
            name='validation',
            field=models.BooleanField(),
        ),
    ]
