# Generated by Django 4.2.25 on 2025-10-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_form_description_alter_form_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
