# Generated by Django 4.2.25 on 2025-10-31 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_process_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_category', to='form.category'),
        ),
    ]
