# Generated by Django 4.2.25 on 2025-10-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_process_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='max',
            field=models.IntegerField(blank=True),
        ),
    ]
