# Generated by Django 4.2.25 on 2025-10-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_alter_form_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='max',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
