# Generated by Django 4.2.25 on 2025-11-03 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_answer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.process')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('process', 'form')},
            },
        ),
    ]
