# Generated by Django 4.2.25 on 2025-11-03 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_processform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='forms',
        ),
    ]
