# Generated by Django 4.2.25 on 2025-11-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_remove_process_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='forms',
            field=models.ManyToManyField(related_name='processes', through='form.ProcessForm', to='form.form'),
        ),
    ]
