# Generated by Django 4.2.25 on 2025-10-31 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0006_process_category'),
        ('conclusion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=0)),
                ('answer_count', models.IntegerField(default=0)),
                ('answer_list', models.JSONField(default=dict)),
                ('mean_rating', models.FloatField(blank=True)),
                ('usable_category', models.CharField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='form.process')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='FormReport',
        ),
    ]
