# Generated by Django 4.2.25 on 2025-10-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclusion', '0002_conclusion_delete_formreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conclusion',
            name='usable_category',
            field=models.CharField(blank=True, null=True),
        ),
    ]
