# Generated by Django 4.2.25 on 2025-10-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclusion', '0003_alter_conclusion_usable_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conclusion',
            name='mean_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
